name: NeoLogin
version: '${version}'
main: com.blbilink.neoLogin.NeoLogin
author: EggFine[blbilink]
description: NeoLogin is a plugin that requires players to login to play. It is NEXT GENERATION of blbiLogin.
api-version: '1.21'
folia-supported: true
load: STARTUP
depend:
  - NeoLibrary
START-AFTER:
  - NeoLibrary


softdepend:
  - floodgate

commands:
  login:
    description: "Login to the server"
    usage: "/login <password>"
    aliases:
      - "l"
  register:
    description: "Register a new account"
    usage: "/register <password> [confirm password]"
    aliases:
      - "reg"
  neologin:
    description: "NeoLogin main command"
    usage: "/neologin <reload|savelocation>"
    aliases:
      - "nl"
    permission: "neologin.admin"
  resetpassword:
    description: "Reset your password"
    usage: "/resetpassword <old password> <new password>"
    aliases:
      - "resetpass"
      - "resetpw"
      - "resetpwd"

permissions:
  neologin.admin:
    description: "Allows access to admin commands"
    default: op